import { chromium } from "@playwright/test";

import { renderResumePrintHtml } from "@/catalog/resume-print-html";

/**
 * Zero volatile PDF metadata so regenerated bytes can be compared to the commit.
 */
export function stabilizePdf(bytes: Uint8Array): Buffer {
  let text = Buffer.from(bytes).toString("latin1");
  text = text.replace(/\/CreationDate\s*\([^)]*\)/g, "/CreationDate (D:19700101000000Z)");
  text = text.replace(/\/ModDate\s*\([^)]*\)/g, "/ModDate (D:19700101000000Z)");
  text = text.replace(
    /\/ID\s*\[\s*<[^>]+>\s*<[^>]+>\s*\]/g,
    "/ID [<00000000000000000000000000000000> <00000000000000000000000000000000>]",
  );
  return Buffer.from(text, "latin1");
}

/** Print the plain Resume HTML to a one-page A4 PDF. */
export async function buildResumePdf(): Promise<Buffer> {
  const browser = await chromium.launch({ headless: true });
  try {
    const page = await browser.newPage();
    await page.setContent(renderResumePrintHtml(), { waitUntil: "load" });
    const pdf = await page.pdf({
      preferCSSPageSize: true,
      printBackground: true,
      margin: { top: "0", right: "0", bottom: "0", left: "0" },
    });
    return stabilizePdf(pdf);
  } finally {
    await browser.close();
  }
}
